name: mltype

on: [push]

jobs:
  build:

    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,mlflow]

    - name: Lint with flake8
      run: |
        flake8 mltype tests setup.py  # see tox.ini for config

    - name: Check style with black
      run: |
        black --check -l 80 mltype tests setup.py

    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle mltype

    - name: Test with pytest
      run: |
        pytest  # see tox.ini for config
